"""Inline SVG for the web view.

Two figures, both drawn from facts the tool already computed rather than
decoration bolted on:

* **Gateway ownership over time** — the timing model's own output, rendered.
  A divergence finding says two groups end up on different devices for ninety
  seconds; this draws it, which is the difference between being told and seeing.
* **Adjacency map** — devices and the subnets they share.

Everything is inline: no external assets, no script dependencies, no build step.
The colours are the validated categorical slots 1 to 3 and the reserved status
palette; every band is directly labelled, which is also the relief the light-mode
contrast check requires.
"""

from __future__ import annotations

import html
import ipaddress
import math
import re
from collections.abc import Callable
from typing import Final

from cassandra.factpack.schema import StaticFactPack
from cassandra.findings import Finding
from cassandra.timing.model import Event, EventKind, simulate

# Categorical slots 1-3, light / dark. Measured as a set in tests/test_palette.py:
# each has to stay distinguishable from the others under red-green colour
# blindness, and each has to carry a readable label — which is what fixes the
# light values darker than the dark ones rather than the other way round.
SERIES: Final = (("#2873cf", "#3987e5"), ("#c94714", "#d95926"), ("#14835c", "#199e70"))
SPLIT_COLOUR: Final = ("#d03b3b", "#d03b3b")  # status: critical
NO_MASTER: Final = ("#8c8b86", "#6f6e69")

# The two candidates for text drawn on a band.
LABEL_LIGHT: Final = "#ffffff"
LABEL_DARK: Final = "#0b0b0b"


def _relative_luminance(colour: str) -> float:
    raw = colour.lstrip("#")
    channels = []
    for index in (0, 2, 4):
        value = int(raw[index : index + 2], 16) / 255
        channels.append(
            value / 12.92 if value <= 0.03928 else ((value + 0.055) / 1.055) ** 2.4
        )
    return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2]


def label_for(fill: str) -> str:
    """Whichever of white or near-black reads better on this fill.

    Band labels are eleven-pixel bold text sitting on the band's own colour, and
    a mid-tone fill cannot carry white text at that size. Choosing per fill
    rather than per theme is what lets the slots stay the colours they are.
    """
    luminance = _relative_luminance(fill)
    against_white = (_relative_luminance(LABEL_LIGHT) + 0.05) / (luminance + 0.05)
    against_dark = (luminance + 0.05) / (_relative_luminance(LABEL_DARK) + 0.05)
    return LABEL_DARK if against_dark > against_white else LABEL_LIGHT


_BAND_H: Final = 26
_BAND_GAP: Final = 10
_LEFT: Final = 92
_RIGHT: Final = 16
_TOP: Final = 26
_WIDTH: Final = 720


def _device_colours(devices: list[str]) -> dict[str, tuple[str, str]]:
    """Colour follows the device, never its rank in a filtered list."""
    return {device: SERIES[i % len(SERIES)] for i, device in enumerate(sorted(devices))}


def _events_from_trigger(trigger: str, pack: StaticFactPack) -> list[Event] | None:
    """Rebuild the simulated sequence from a finding's trigger line.

    The trigger is generated by `timing/sequences.py` in one of two fixed
    shapes, so this reads its own output rather than guessing at free text.
    Returns None when neither shape matches, and the caller draws no figure —
    an invented sequence under a real finding would be worse than no picture.
    """
    text = trigger.strip()
    if m := re.fullmatch(r"flap (\S+):(\S+) (\d+)x \((\d+)s down, (\d+)s up\)", text):
        device, interface, flaps, down_s, up_s = m.groups()
        events: list[Event] = []
        clock = 0
        for _ in range(int(flaps)):
            events.append(
                Event(
                    at_ms=clock,
                    kind=EventKind.LINK_DOWN,
                    device=device,
                    interface=interface,
                )
            )
            clock += int(down_s) * 1000
            events.append(
                Event(
                    at_ms=clock,
                    kind=EventKind.LINK_UP,
                    device=device,
                    interface=interface,
                )
            )
            clock += int(up_s) * 1000
        return events

    if m := re.fullmatch(r"reload (\S+) \((\d+)s down\)", text):
        device, down_s = m.groups()
        names = [
            interface.name
            for entry in pack.devices
            if entry.id == device
            for interface in entry.interfaces
        ]
        if not names:
            return None
        return [
            Event(at_ms=at, kind=kind, device=device, interface=name)
            for at, kind in (
                (0, EventKind.LINK_DOWN),
                (int(down_s) * 1000, EventKind.LINK_UP),
            )
            for name in names
        ]
    return None


def timeline_svg(pack: StaticFactPack, finding: Finding) -> str:
    """Which device holds each FHRP group, second by second, under the trigger."""
    if not finding.trigger:
        return ""
    events = _events_from_trigger(finding.trigger, pack)
    if not events or not pack.fhrp_groups:
        return ""
    horizon = max(event.at_ms for event in events) + 120_000
    timeline = simulate(pack, events, until_ms=horizon)
    if not timeline:
        return ""

    groups = [g for g in pack.fhrp_groups]
    labels = {g.id: f"{g.protocol.value.upper()} {g.group_number}" for g in groups}
    holders = sorted(
        {
            master
            for sample in timeline
            for master in sample.masters.values()
            if master and master != "SPLIT"
        }
    )
    colours = _device_colours(holders)

    plot_w = _WIDTH - _LEFT - _RIGHT
    height = _TOP + len(groups) * (_BAND_H + _BAND_GAP) + 34
    span = max(timeline[-1].at_ms, 1)

    def x(at_ms: int) -> float:
        return _LEFT + plot_w * at_ms / span

    parts: list[str] = [
        f'<svg class="viz timeline" viewBox="0 0 {_WIDTH} {height}" '
        f'role="img" aria-label="Gateway ownership over time under the trigger">'
    ]

    # Event markers first, so bands sit above them.
    for event in events:
        down = event.kind is EventKind.LINK_DOWN
        parts.append(
            f'<line class="ev" x1="{x(event.at_ms):.1f}" y1="{_TOP - 12}" '
            f'x2="{x(event.at_ms):.1f}" y2="{height - 30}" '
            f'stroke-dasharray="{"3 3" if down else "1 4"}"/>'
        )

    for row, group in enumerate(groups):
        y = _TOP + row * (_BAND_H + _BAND_GAP)
        parts.append(
            f'<text class="row-label" x="{_LEFT - 10}" y="{y + _BAND_H / 2 + 4}" '
            f'text-anchor="end">{html.escape(labels[group.id])}</text>'
        )
        # Collapse consecutive identical holders into one band.
        runs: list[tuple[int, int, str | None]] = []
        for sample in timeline:
            master = sample.masters.get(group.id)
            if runs and runs[-1][2] == master:
                runs[-1] = (runs[-1][0], sample.at_ms, master)
            else:
                runs.append((sample.at_ms, sample.at_ms, master))

        for start, end, master in runs:
            width = max(x(end) - x(start) - 2, 2)  # 2px surface gap between fills
            if master == "SPLIT":
                light, dark = SPLIT_COLOUR
                title = "two masters at once"
            elif master is None:
                light, dark = NO_MASTER
                title = "no master"
            else:
                light, dark = colours[master]
                title = master
            parts.append(
                f'<g class="band" style="--c:{light};--cd:{dark};'
                f'--l:{label_for(light)};--ld:{label_for(dark)}">'
                f'<rect x="{x(start):.1f}" y="{y}" '
                f'width="{width:.1f}" height="{_BAND_H}" rx="4">'
                f"<title>{html.escape(title)} "
                f"{start // 1000}s-{end // 1000}s</title></rect>"
            )
            if width > 54 and master:
                parts.append(
                    f'<text class="band-label" x="{x(start) + 7:.1f}" '
                    f'y="{y + _BAND_H / 2 + 4}">{html.escape(str(master))}</text>'
                )
            parts.append("</g>")

    for tick in range(0, span + 1, max(30_000, span // 6 // 1000 * 1000 or 30_000)):
        parts.append(
            f'<text class="tick" x="{x(tick):.1f}" y="{height - 10}" '
            f'text-anchor="middle">{tick // 1000}s</text>'
        )

    parts.append("</svg>")
    return "".join(parts)


def topology_svg(
    pack: StaticFactPack,
    link: Callable[[str], str] | None = None,
    marks: dict[str, str] | None = None,
) -> str:
    """Devices, and the subnets they share.

    Uses derived L3 adjacency when the fact pack has it and falls back to
    computing shared subnets directly, so the figure appears either way.

    When `link` is given, each node becomes a link to what it returns for that
    device. The map is the only place on the page that shows a device someone
    has no finding for, so being able to click one is the difference between a
    picture and a control.

    `marks` maps a device to the severity of its worst finding, drawn as a dot
    on its node. It turns the map from a diagram of the network into a summary
    of the result — where the trouble is, before reading a word of it.
    """
    edges = _edges(pack)
    devices = sorted({d.id for d in pack.devices})
    if len(devices) < 2 or not edges:
        return ""

    linked = {device for edge in edges for device in edge[:2]}
    connected = [d for d in devices if d in linked]
    detached = [d for d in devices if d not in linked]

    width = 720
    height = 250 + (62 if detached else 0)
    cx, cy = width / 2, 128
    radius = 90

    # Connected devices ring the centre. Unattached ones get their own row
    # instead of a slot in the ring, where they push the real topology apart and
    # imply an adjacency that is not there.
    positions: dict[str, tuple[float, float]] = {}
    for i, device in enumerate(connected):
        angle = -math.pi / 2 + 2 * math.pi * i / max(len(connected), 1)
        positions[device] = (
            cx + radius * math.cos(angle),
            cy + radius * math.sin(angle),
        )
    for i, device in enumerate(detached):
        step = width / (len(detached) + 1)
        positions[device] = (step * (i + 1), height - 48)

    parts: list[str] = [
        f'<svg class="viz topology" viewBox="0 0 {width} {height}" role="img" '
        f'aria-label="Devices and the subnets they share">'
    ]
    for index, (a, b, subnets) in enumerate(edges):
        (x1, y1), (x2, y2) = positions[a], positions[b]
        label = subnets[0] if len(subnets) == 1 else f"{len(subnets)} subnets"
        parts.append(
            f'<g class="edge" style="--i:{index}">'
            f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}"/>'
            f"<title>{html.escape(', '.join(subnets))}</title>"
            f'<text class="edge-label" x="{(x1 + x2) / 2:.1f}" '
            f'y="{(y1 + y2) / 2 - 5 + (index % 2) * 13:.1f}" text-anchor="middle">'
            f"{html.escape(label)}</text></g>"
        )
    addressed = {
        device.id
        for device in pack.devices
        if any(interface.addresses for interface in device.interfaces)
    }
    for index, device in enumerate(devices):
        x, y = positions[device]
        # Two different situations, and labelling both "L2 only" was wrong. A
        # switch with no addresses genuinely is layer 2. An addressed device on
        # nobody else's subnet is simply not adjacent to anything in this
        # directory, usually because its peer is not in the corpus.
        detached = device not in linked
        hint = (
            ""
            if not detached
            else ("L2 only" if device not in addressed else "no peer here")
        )
        isolated = " l2only" if detached else ""
        title = (
            ""
            if not detached
            else "<title>"
            + (
                "no addressed interface: layer 2 only"
                if device not in addressed
                else "addressed, but shares no subnet with any device here"
            )
            + "</title>"
        )
        severity = (marks or {}).get(device, "")
        badge = (
            ""
            if not severity
            else f'<circle class="mark {html.escape(severity)}" '
            f'cx="{x + 8:.1f}" cy="{y - 8:.1f}" r="4.5"/>'
        )
        node = (
            f'<g class="node{isolated}" style="--i:{index}">'
            f'<circle cx="{x:.1f}" cy="{y:.1f}" r="9"/>{title}{badge}'
            f'<text x="{x:.1f}" y="{y - 16:.1f}" text-anchor="middle">'
            f"{html.escape(device)}</text>"
            + (
                ""
                if not hint
                else f'<text class="hint" x="{x:.1f}" y="{y + 24:.1f}" '
                f'text-anchor="middle">{hint}</text>'
            )
            + "</g>"
        )
        # An empty string means "no link for this one" — a device with nothing to
        # show should not look clickable and then do nothing.
        target = link(device) if link is not None else ""
        if target:
            node = f'<a href="{target}" class="node-link">{node}</a>'
        parts.append(node)
    parts.append("</svg>")
    return "".join(parts)


def _edges(pack: StaticFactPack) -> list[tuple[str, str, list[str]]]:
    """Device pairs sharing a subnet, with the subnets that join them."""
    shared: dict[tuple[str, str], set[str]] = {}

    if pack.l3_adjacencies:
        for adjacency in pack.l3_adjacencies:
            members = sorted({m.device for m in adjacency.members})
            for i, a in enumerate(members):
                for b in members[i + 1 :]:
                    shared.setdefault((a, b), set()).add(adjacency.prefix)
    else:
        by_device: dict[str, set[str]] = {}
        for device in pack.devices:
            for interface in device.interfaces:
                for assignment in interface.addresses:
                    try:
                        net = str(ipaddress.ip_interface(assignment.prefix).network)
                    except ValueError:
                        continue
                    by_device.setdefault(device.id, set()).add(net)
        names = sorted(by_device)
        for i, a in enumerate(names):
            for b in names[i + 1 :]:
                common = by_device[a] & by_device[b]
                if common:
                    shared[(a, b)] = common

    return [(a, b, sorted(nets)) for (a, b), nets in sorted(shared.items())]


def sparkbar(counts: dict[str, int], colours: dict[str, str]) -> str:
    """A one-row proportional bar of finding counts by severity."""
    total = sum(counts.values())
    if not total:
        return ""
    parts = ['<div class="sparkbar" role="img" aria-label="findings by severity">']
    for key, count in counts.items():
        if not count:
            continue
        pct = 100 * count / total
        parts.append(
            f'<span class="seg" style="width:{pct:.2f}%;--c:{colours[key]}" '
            f'title="{count} {html.escape(key)}"></span>'
        )
    parts.append("</div>")
    return "".join(parts)


# --------------------------------------------------------------------------
# How the groups are configured to react
# --------------------------------------------------------------------------

_ROW_H: Final = 30
_REACT_W: Final = 720


def _group_reaction(pack: StaticFactPack) -> list[tuple[str, int, int, bool]]:
    """Per group: label, preempt delay in seconds, tracked decrement, preempt.

    The delay and the decrement are taken from the member that has them. A group
    where one member tracks and the other does not still reacts, and it is the
    tracking member's numbers that decide how.
    """
    delays: dict[tuple[str, str | None, str | None], int] = {}
    for timer in pack.timers.fhrp:
        if timer.preempt_delay_ms:
            key = (timer.scope.device, timer.scope.interface, timer.scope.instance)
            delays[key] = timer.preempt_delay_ms

    rows: list[tuple[str, int, int, bool]] = []
    for group in pack.fhrp_groups:
        delay_ms = 0
        decrement = 0
        preempt = False
        for member in group.members:
            key = (member.device, member.interface, str(group.group_number))
            delay_ms = max(delay_ms, delays.get(key, 0))
            decrement = max(
                decrement,
                *(t.decrement for t in member.tracked_objects),
                0,
            )
            preempt = preempt or member.preempt
        label = f"{group.protocol.value.upper()} {group.group_number}"
        rows.append((label, delay_ms // 1000, decrement, preempt))
    return rows


def reaction_svg(pack: StaticFactPack) -> str:
    """What each group does when the thing it tracks goes down.

    The timeline draws the effect; this draws the cause. A divergence is two
    rows here that do not match — one group waiting ninety seconds to take back
    what another took back immediately — and seeing the rows side by side is
    what turns "these two ended up apart" into "of course they did".

    Empty for fewer than two groups: one row compared against nothing is a fact
    already stated in the finding.
    """
    rows = _group_reaction(pack)
    if len(rows) < 2:
        return ""

    height = _TOP + len(rows) * _ROW_H + 34
    max_delay = max((delay for _, delay, _, _ in rows), default=0)
    max_decrement = max((d for _, _, d, _ in rows), default=0)
    left, gap = 92, 26
    column = (_REACT_W - left - _RIGHT - gap) / 2

    parts = [
        f'<svg class="viz reaction" viewBox="0 0 {_REACT_W} {height}" role="img" '
        f'aria-label="Preempt delay and tracked decrement for each group">'
        f'<text class="col" x="{left}" y="16">preempt delay</text>'
        f'<text class="col" x="{left + column + gap:.0f}" y="16">'
        f"tracked decrement</text>"
    ]
    for index, (label, delay, decrement, preempt) in enumerate(rows):
        y = _TOP + index * _ROW_H
        mid = y + _ROW_H / 2 - 2
        parts.append(
            f'<text class="row-label" x="{left - 10}" y="{mid + 4}" '
            f'text-anchor="end">{html.escape(label)}</text>'
        )
        for offset, value, ceiling, unit in (
            (0.0, delay, max_delay, "s"),
            (column + gap, decrement, max_decrement, ""),
        ):
            x = left + offset
            # The value is written after the bar, so the bar cannot use the
            # whole column or the number falls off the edge of the figure.
            span = column - 46
            width = 0.0 if not ceiling else span * value / ceiling
            if value:
                parts.append(
                    f'<g class="bar" style="--i:{index}">'
                    f'<rect x="{x:.1f}" y="{y}" width="{max(width, 3):.1f}" '
                    f'height="{_ROW_H - 12}" rx="3"/></g>'
                    f'<text class="value" x="{x + max(width, 3) + 6:.1f}" '
                    f'y="{mid + 4}">{value}{unit}</text>'
                )
            else:
                # A zero bar is invisible, and "none" is the whole point of the
                # row it appears in: this group does not wait, or does not track.
                parts.append(
                    f'<text class="value none" x="{x:.1f}" y="{mid + 4}">'
                    f"{'none' if not preempt or unit else 'no tracking'}</text>"
                )
    parts.append("</svg>")
    return "".join(parts)
